#  **Практическое занятие №2. Линейная алгебра.**

## Знакомство с библиотекой **NumPy**

numpy - библиотека для быстрой работы с большими массивами и матрицами

https://numpy.org/doc/stable/user/quickstart.html

In [2]:
import numpy as np

### Мотивация: numpy vs python

In [ ]:
import time

arr_size = 1000000
iter_num = 900

In [ ]:
# time pure python list sum
x = list(range(arr_size))

s = time.time()

for i in range(iter_num):
    sum(x)

t = time.time() - s

print(f'Finished in {t:.5f} s: {(t * 1000 / iter_num):.5f} ms per iteration')

Finished in 7.15435 s: 7.94928 ms per iteration


In [ ]:
# time numpy array sum
x = np.arange(arr_size)

s = time.time()

for i in range(iter_num):
    np.sum(x)

t = time.time() - s

print(f'Finished in {t:.5f} s: {(t * 1000 / iter_num):.5f} ms per iteration')

Finished in 0.33990 s: 0.37766 ms per iteration


### Basics

#### Создание массива
https://numpy.org/doc/stable/reference/routines.array-creation.*html*

In [ ]:
# создать явно
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# нулевой массив заданного размера
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# нулевой массив такого же размера, как другой
a = np.array([[1, 2, 3], [4, 5, 6]])
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# массив единиц заданного размера
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# массив единиц такого же размера, как другой
a = np.array([[1, 2, 3], [4, 5, 6]])
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
# массив, заполненный конкретным числом
np.full((2, 3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
# массив, заполненный конкретным числом
a = np.array([[1, 2, 3], [4, 5, 6]])
np.full_like(a, 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [ ]:
# создать единичную матрицу (двумерный массив)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# создать range
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [ ]:
# можно явно указать тип при создании массива вторым аргументов
np.zeros((2, 3), dtype=np.double)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# заполнить из функции
np.fromfunction(lambda i, j: i * j, (3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
# можно заменить тип
a = np.array([1, 2, 5])
a.astype('str')

array(['1', '2', '5'], dtype='<U21')

In [ ]:
# посмотреть все возможные типы
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64, numpy.longdouble],
 'complex': [numpy.complex64, numpy.complex128, numpy.clongdouble],
 'others': [bool, object, bytes, str, numpy.void]}

#### Доступ к элементам массива, срезы
https://numpy.org/doc/stable/user/basics.indexing.html



##### Доступ к элементам

In [ ]:
# доступ по индексу, включая негативные индексы
a = np.arange(10)
a[-2]

8

In [ ]:
# доступ по набору индексов, включая негативные
a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
a[1,4]

9

In [ ]:
# можно выделять индекс по каждому срезу отдельными скобками - но это менее эффективно
a[1][3] # same as a[1,3]

8

In [ ]:
# можно изменять значение по индексу
a = np.arange(5)
a[0] = 5
a

##### Срезы, слайсы

In [6]:
a = list(range(10))
a[8:1:-2]

[8, 6, 4, 2]

In [5]:
# работает привычный питонячий слайсинг
a = np.arange(10)
a[8:1:-2]

array([8, 6, 4, 2])

In [3]:
# срез по первой оси
a = np.array([[[0, 1, 2],[3, 4, 5]],[[6, 7, 8],[9, 10, 11]]])
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [4]:
a.shape

(2, 2, 3)

In [5]:
a[0] # same as a[0,:,:]

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
# срез по произвольной оси
a = np.array([[[0, 1, 2],[3, 4, 5]],[[6, 7, 8],[9, 10, 11]]])
a[:,:,0] # same as a[:,0,:]

array([[0, 3],
       [6, 9]])

In [7]:
# срез + слайс
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])
a[0,-1:0:-2]

array([3, 1])

In [8]:
a.copy()

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
# можно задавать срезы/слайсы программно
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11]])

i = np.array([0, 2])
s = slice(-1, 0, -2)

a[i,s]

array([[ 3,  1],
       [11,  9]])

In [ ]:
a[np.array([0, 2]),-1:0:-2]

In [ ]:
# !!! срезы/слайсы не копируют массивы, а возвращают "представление"
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11]])

b = a[0]
b[2] = 100

a

Задача. Создать матрицу с единицами на побочной диагонали и нулями вне ее.

In [19]:
matrix = np.eye(5)[:,::-1]
matrix

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

##### Форма массива и ее изменение

In [20]:
a = np.arange(12)
a.shape

(12,)

In [25]:
b = a.reshape(2, 6)
b.shape
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [23]:
# важно сохранять размеры при изменении формы
c = a.reshape(2, 6)

In [30]:
# можно использовать -1, тогда размер вдоль этой оси будет автоматически вычисляться
c = a.reshape(5, -1)
c.shape

(5, 2)

In [26]:
# развернуть массив в одномерный
d = c.ravel()
d.shape

(12,)

In [27]:
# !!! изменение формы тоже возвращает "представление"
a = np.arange(10)

b = a.reshape(2, 5)
b[0][3] = 100

a

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

#### Операции с массивами

##### Арифметические операции

Операции с числами выполняются **поэлементно**



In [31]:
a = np.array([[1, 2],[3, 4]])
a

array([[1, 2],
       [3, 4]])

In [32]:
a + 1

array([[2, 3],
       [4, 5]])

In [33]:
a - 1

array([[0, 1],
       [2, 3]])

In [34]:
a * 2

array([[2, 4],
       [6, 8]])

In [35]:
a / 2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [36]:
a ** 2

array([[ 1,  4],
       [ 9, 16]])

Математические операции между матрицами тоже выполняются **поэлементно**

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[3, 4], [1, 2]])

In [ ]:
a + b

In [ ]:
a - b

In [ ]:
a * b

In [ ]:
a / b

Формы массивов могут не совпадать, главное - чтобы они были **broadcastable**

https://numpy.org/doc/stable/user/basics.broadcasting.html

In [37]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([0, 1, 2])
c = np.array([[0, 1, 2], [0, 1, 2]])

print(a.shape, b.shape, c.shape)

(2, 3) (3,) (2, 3)


In [38]:
a + b

array([[1, 3, 5],
       [4, 6, 8]])

In [39]:
a + c

array([[1, 3, 5],
       [4, 6, 8]])

Задача. Создать квадратную матрицу размера N с квадратами чисел от N до 1 на главной диагонали

In [40]:
# your code here
a = np.eye(10)
b = np.arange(10, 0, -1)
c = (a * b) ** 2

c

array([[100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  81.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,  64.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  49.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  36.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,  25.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,  16.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   9.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   4.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.]])

##### Математические функции

https://numpy.org/doc/stable/reference/routines.math.html

In [41]:
# поэлементные функции
a = np.arange(10)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [3]:
# агрегатные функции
a = np.array([[1, 2], [3, 4]])
np.sum(a)

10

In [4]:
# можно задавать ось
a = np.array([[1, 2], [3, 4]])
np.sum(a, 0)
a

array([[1, 2],
       [3, 4]])

##### Матричные операции

Транспонирование матрицы

In [45]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [46]:
a.T

array([[1, 3],
       [2, 4]])

In [47]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [48]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

Операция matmul - умножение матрицы на вектор, и матрицы на матрицу

https://numpy.org/doc/stable/reference/generated/numpy.matmul.html

In [50]:
# два вектора - скалярное произведение
a = np.array([2., 3., 4.])
b = np.array([-2., 1., -1.])

np.matmul(a, b)

-5.0

In [ ]:
# матрица и вектор - умножение матрицы на вектор
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([-1, 3, 2])

a @ b

In [52]:
# две матрицы
a = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])
b = np.array([[1, 2], [3, 4], [5, 6]])

a @ b

array([[22, 28],
       [40, 52],
       [58, 76]])

In [53]:
# важно, чтобы матрицы соответствовали по размеру (число столбцов первой матрицы равнялось число строк второй)
b @ a

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [55]:
# если размерность одного массива больше 2?
a = np.ones((12, 5, 3, 4))
b = np.ones((4, 5))

c = a @ b
c.shape
c

array([[[[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]],

        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]],

        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]],

        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]],

        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]]],


       [[[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]],

        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]],

        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]],

        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]],

        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]]],


       [[[4., 4., 4., 4., 4.],
         [4., 4

In [57]:
# а если обоих?
a = np.ones((2, 3, 4))
b = np.ones((2, 4, 5))

c = a @ b
c.shape
c

array([[[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]]])

Операция dot - тоже умножение, но есть нюанс

https://numpy.org/doc/stable/reference/generated/numpy.dot.html

In [61]:
# если размерность одного массива больше 2?
a = np.ones((2, 3, 4))
b = np.ones((4, 5))

c = a.dot(b)
c.shape
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# а если обоих?
a = np.ones((2, 3, 4))
b = np.ones((7, 4, 5))

c = a.dot(b)
c.shape

Обратная матрица и определитель

In [ ]:
# определитель
a = np.eye(10)

print(a)
print(np.linalg.det(a))

In [70]:
b = 5 * np.eye(6) + np.ones(6)

print(b)
print(np.linalg.det(b))

[[6. 1. 1. 1. 1. 1.]
 [1. 6. 1. 1. 1. 1.]
 [1. 1. 6. 1. 1. 1.]
 [1. 1. 1. 6. 1. 1.]
 [1. 1. 1. 1. 6. 1.]
 [1. 1. 1. 1. 1. 6.]]
34374.99999999999


In [69]:
# обратная матрица
a = np.array([[1, 2], [3, 4]])
b = np.linalg.inv(a)

b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [64]:
a @ b

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [66]:
np.allclose(a @ b, np.eye(2))

False

In [65]:
# обратная матрица не всегда существует
a = np.array([[1, 0], [2, 0]])
np.linalg.det(a)

0.0

Задача. Решить систему линейных уравнений
$$
a_{11} x_1 + ... + a_{1n} x_n = b_1
$$
$$
...
$$
$$
a_{n1} x_1 + ... + a_{nn} x_n = b_n
$$

В матричном виде $Ax = b$

In [67]:
def solve_eq(A, b):
    return np.linalg.inv(A) @ b

In [68]:
A = np.random.random((5, 5))
b = np.arange(5)

x = solve_eq(A, b)

assert np.allclose(A @ x, b)